const RESOURSES_NAMES_ENUM=['customer','category','order','product']

const RESOURSES_NAMES={
    CUSTOMER:RESOURSES_NAMES_ENUM[0],
    CATEGORY:RESOURSES_NAMES_ENUM[1],
    ORDER:RESOURSES_NAMES_ENUM[2],
    PRODUCT:RESOURSES_NAMES_ENUM[3],
}

const ACTIONS_NAMES_ENUM=['readAny','readOwn','deleteAny','deleteOwn','updateAny','updateOwn','createAny','createOwn']

const ACTIONS_NAMES={
    READ_ANY:ACTIONS_NAMES_ENUM[0],
    READ_OWN:ACTIONS_NAMES_ENUM[1],
    DELETE_ANY:ACTIONS_NAMES_ENUM[2],
    DELETE_OWN:ACTIONS_NAMES_ENUM[3],
    UPDATE_ANY:ACTIONS_NAMES_ENUM[4],
    UPDATE_OWN:ACTIONS_NAMES_ENUM[5],
    CREATE_ANY:ACTIONS_NAMES_ENUM[6],
    CREATE_OWN:ACTIONS_NAMES_ENUM[7],

}

module.exports={
    RESOURSES_NAMES,
    ACTIONS_NAMES
}